### ISSUE TITLE
Validation des données d'import

### ISSUE THREAD

**Issue by cdugeai** [DITP-pilotage/pilote-2#17]
Idées pour automatiser la cohérence des données d'imports:

- Créer un [TableSchema](https://specs.frictionlessdata.io/table-schema/) qui permet de spécifier un format de données tabulaires
- Utiliser l'API [validata](https://validata.fr/) pour valider des données contre un schéma (lien pour [tester l'API](https://api.validata.etalab.studio/apidocs#/))

Et éventuellement automatiser leur import sur [data.gouv](https://www.data.gouv.fr) :
- Publier le schema sur [schema.data.gouv.fr](http://schema.data.gouv.fr/) (voir le [guide](https://guides.etalab.gouv.fr/producteurs-schemas/aide-construction-tableschema/#recommandations-pour-le-formatage-des-fichiers-csv) par Etablab pour créer le TableSchema)
- Utiliser [publier.etalab.studio](https://publier.etalab.studio/) pour permettre la vérification de la donnée saisie et sa publication automatique sur [data.gouv](https://www.data.gouv.fr)

**Comment by geoffreyaldebert** [comment]
Top ! Welcome in table schema world ;)

Les schémas sur schema.data.gouv.fr ont vocation à être utilisés par plusieurs acteurs. Dans votre cas d'usage, il n'y a peut-être que votre organisation qui utilise les schémas créés. Cela ne change pas le fait que ce soit intéressant d'utiliser ces schémas pour contrôler la qualité de vos données.
Nous travaillons avec l'ANCT en ce moment pour voir dans quelle mesure data.gouv.fr pourrait supporter des schémas "communautaires" (publié par un acteur indépendamment de schema.data.gouv.fr). Votre cas d'usage semble également rentrer dans ce schéma. On va donc en reparler en équipe pour voir comment prioriser ces nouveaux dev sur data.gouv.fr dans les prochaines semaines.

FYI @agaronne @maudetes

**Comment by Maxgux** [comment]
On ferme cette issue ?

**Comment by cdugeai** [comment]
Oui, on traite ça en parallèle
