### ISSUE TITLE
Les transformations DBT réécrivent le schéma de la base

### ISSUE THREAD

**Issue by FabienRoussel** [DITP-pilotage/pilote-2#55]
L'exécution des pipelines DBT écrit par dessus le schéma de la table même si celui-ci n'est pas le même.

Par exemple pour la table public.chantier, si l'ordre de sélection des colonne de la transformation DBT n'est pas le même que des champs dans la table, alors le schéma est réécrit par DBT. Cela pourrait notamment poser problèmes sur les types si ceux ci sont amenés à être modifié involontairement par DBT.

**Comment by FabienRoussel** [comment]
Du coup, pour la réalisation du ticket 87 sur la transformation des données brutes des indicateurs vers la table public.indicateur, il a été préféré de le faire en SQL simplement et de l'exécuter avec PSQL. 

Il faudrait refacto ça quand on aura la solution

**Comment by Maxgux** [comment]
On ferme cette issue ?
