### ISSUE TITLE
Questionnement sur le stockage des données des filtres

### ISSUE THREAD

**Issue by FabienRoussel** [DITP-pilotage/pilote-2#58]
Problématique : 
Certaines données, tels que les périmètres, sont utilisés pour faire des filtres sur le front-end. A l'heure actuelle les données sont en dur dans une énumération dans le front-end. 
Cependant certaines données pourraient sensibles et il ne faudrait pas y avoir accès directement sur github. 
De plus, on ne sait pas si ces données peuvent changer régulièrement et si donc il faudrait les stocker dans un back-office.

Je vous propose donc de voter pour les solutions ci-dessous :

**Comment by FabienRoussel** [comment]
Solution 1 : 
On stock l'ensemble des données des filtres dans des tables public et on se sert de ces tables pour alimenter nos filtres.

**Comment by FabienRoussel** [comment]
Solution 2 :
On met l'ensemble des données dans des énumérations dans le front-end ou le back-end et on se sert de ces énumérations pour alimenter nos filtres.

**Comment by Maxgux** [comment]
On ferme cette issue ?
